# Generated by Django 3.2.7 on 2022-03-03 04:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0002_auto_20220303_1035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingredients',
            name='Rm_name',
        ),
        migrations.AddField(
            model_name='ingredients',
            name='Rm_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='modul.rawmaterial', verbose_name='Сырьё'),
        ),
    ]
