# Generated by Django 3.2.7 on 2022-03-07 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0003_auto_20220303_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='budjet',
            name='Date',
            field=models.DateField(default=None, null=True, verbose_name='дата продажи'),
        ),
        migrations.AddField(
            model_name='budjet',
            name='Procent',
            field=models.IntegerField(default=0, verbose_name='процент прибыли'),
        ),
    ]
