# Generated by Django 3.2.7 on 2022-03-17 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0004_auto_20220307_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingredients',
            name='Amount',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='production',
            name='Amount',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Amount',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='products',
            name='Summ',
            field=models.FloatField(default=0, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='purrawmaterial',
            name='Amount',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='purrawmaterial',
            name='Summ',
            field=models.FloatField(default=0, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='Amount',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='Summ',
            field=models.FloatField(default=0, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='Amount',
            field=models.FloatField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='saleproduct',
            name='Summ',
            field=models.FloatField(default=0, verbose_name='Сумма'),
        ),
    ]
