# Generated by Django 3.2.7 on 2022-03-24 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0005_auto_20220317_1134'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='budjet',
            name='Date',
        ),
        migrations.AddField(
            model_name='budjet',
            name='Bonus',
            field=models.IntegerField(default=0, verbose_name='Бонус'),
        ),
    ]
