# Generated by Django 3.2.7 on 2022-03-24 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0006_auto_20220324_0926'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salaries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Month', models.CharField(default=3, max_length=255, verbose_name='Месяц выдачи')),
                ('Purchases', models.IntegerField(default=0, verbose_name='Покупка')),
                ('Sales', models.IntegerField(default=0, verbose_name='Продажа')),
                ('Production', models.IntegerField(default=0, verbose_name='Производство')),
                ('TotalPart', models.IntegerField(default=0, verbose_name='Участие')),
                ('Bonus', models.IntegerField(default=0, verbose_name='Бонус')),
                ('TotalSum', models.IntegerField(default=0, verbose_name='Сумма выдачи')),
                ('IsGiven', models.BooleanField(default=False, verbose_name='Выдано')),
                ('Name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='modul.employees', verbose_name='Имя сотрудника')),
            ],
            options={
                'verbose_name': 'Выдача ЗП',
                'verbose_name_plural': 'Выдача ЗП',
            },
        ),
    ]
