# Generated by Django 3.2.7 on 2022-03-24 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0007_salaries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='Month',
            field=models.IntegerField(default='March', verbose_name='Месяц выдачи'),
        ),
    ]
