# Generated by Django 3.2.7 on 2022-03-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0008_alter_salaries_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='Month',
            field=models.CharField(default='March', max_length=255, verbose_name='Месяц выдачи'),
        ),
    ]
