# Generated by Django 3.2.7 on 2022-04-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0009_alter_salaries_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='salaries',
            name='Salary',
            field=models.IntegerField(default=0, verbose_name='Оклад'),
        ),
        migrations.AddField(
            model_name='salaries',
            name='Year',
            field=models.IntegerField(default=0, verbose_name='Год выдачи'),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='Month',
            field=models.CharField(default='April', max_length=255, verbose_name='Месяц выдачи'),
        ),
        migrations.AlterField(
            model_name='salaries',
            name='TotalSum',
            field=models.IntegerField(default=0, verbose_name='Общая сумма'),
        ),
    ]
