# Generated by Django 3.2.7 on 2022-04-10 15:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('modul', '0012_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salaries',
            name='Month',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='modul.month'),
        ),
    ]
